INSERT INTO location (city, village) VALUES
     ('Colombo', 'Pettah'),
     ('Kandy', 'Peradeniya'),
     ('Galle', 'Unawatuna'),
     ('Matara', 'Weligama'),
     ('Jaffna', 'Chunnakam'),
     ('Anuradhapura', 'Mihintale'),
     ('Polonnaruwa', 'Medirigiriya'),
     ('Badulla', 'Bandarawela'),
     ('Nuwara Eliya', 'Hatton'),
     ('Ratnapura', 'Pelmadulla'),
     ('Kurunegala', 'Pannala'),
     ('Batticaloa', 'Kattankudy'),
     ('Trincomalee', 'Kinniya'),
     ('Puttalam', 'Chilaw'),
     ('Ampara', 'Kalmunai'),
     ('Hambantota', 'Tangalle'),
     ('Mannar', 'Pesalai'),
     ('Kilinochchi', 'Pallai'),
     ('Monaragala', 'Wellawaya'),
     ('Vavuniya', 'Omanthai'),
     ('Kalutara', 'Beruwala'),
     ('Gampaha', 'Negombo'),
     ('Matale', 'Dambulla'),
     ('Kegalle', 'Mawanella'),
     ('Udawalawa', 'Embilipitiya');